#!/bin/sh

# Copy all files in $SRCPATH to $DSTPATH

SRCPATH="clients/mod/assignment/type/onlinejudge/"
DSTPATH="../../mod/assignment/type/onlinejudge"

if [ -e $DSTPATH ]; then
    rm -rf $DSTPATH
fi

cp -rp $SRCPATH $DSTPATH
