#!/bin/sh

# Copy all files in $SRCPATH to $DSTPATH

SCRIPTPATH=`dirname $0`
SRCPATH="$SCRIPTPATH/../clients/mod/assignment/type/onlinejudge/"
DSTPATH="$SCRIPTPATH/../../../mod/assignment/type/onlinejudge"

if [ -e $DSTPATH ]; then
    rm -rf $DSTPATH
fi

cp -rp $SRCPATH $DSTPATH
